### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by maxbailey**
@rentzso want to take a look at this? I think all of this should be up to date with new-ui-integration.

### CODE REVIEW

**Comment by rentzso** [comment]
could you rebase the branch and clean the diff?
Not sure why but there is some extra code shown in that.
There is also a .DS_Store file that should be removed.

**Comment by rentzso** [comment]
icons looks good though!

**Comment by gsfr** [comment]
I just applied the new icon files manually to the `new-ui-integration` branch. Closing this PR.

Thanks, @maxbailey.

**Comment by maxbailey** [comment]
Sounds good, thanks guys.

**Pull request closed without merging**
