### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by cgc**
This PR gets organizer running on a windows 7 instance from [Microsoft's free VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). I was able to get a hint about this issue by running `Organizer.exe --enable-logging` from the command line. The consistent error was a "Javascript heap out of memory". increasing the memory on the box (to 1.5 gig from 500meg) didn't help. changing the `max_old_space_size` didn't help either, but some settings caused faster crashes. so I tried removing this line and it worked! now it's tucked under a `process.platform` check.

### CODE REVIEW

**Comment by gsfr** [comment]
This is great. Thanks, @cgc.

Will we ever be able to cross-build a Windows executable on OS X, or the other way around?

**Comment by cgc** [comment]
@gsfr that actually comes out of the box (well, you'll need to install `wine` on a mac)! So the windows VM I mention above was solely booted to test the generated exe (which, unfortunately, comes with a bunch of dll files. we might do well to integrate with https://github.com/electron-userland/electron-builder eventually if we want the windows UX to be better. This is fine for this use-case in which I'm manually configuring the windows machine.)

**Comment by gsfr** [comment]
I've had a hard time in the past distinguishing between electron-packager and electron-builder. I'd be grateful for further contributions in this direction. Being able to build for all three major platforms would be ideal.

**Comment by cgc** [comment]
packager gives you a directory with an `exe` and some `dlls`. builder gives you an exe that starts an installer for your app. builder also does some legwork in making auto updating easy. would be nice to be working for all 3 platforms!

**Pull request merged**
